#!/usr/bin/env python3
"""Export latest KNN per-analyte probabilities into a Dart file for the app.

Usage:
  python pipeline/export_knn_probs.py \ 
      --input pipeline/dataset/latest_knn_probs.json \ 
      --output uritect_app/lib/models/knn_probabilities.dart

The input JSON should be a simple mapping of analyte codes to probabilities, e.g.
{ "GLU": 0.12, "LEU": 0.6, "PRO": 0.1, "NIT": 0.05 }
"""
from __future__ import annotations
import json
import argparse
from pathlib import Path

TEMPLATE = """// Auto-generated KNN probabilities for dipstick analytes.
// Generated by pipeline/export_knn_probs.py

/// Map from analyte code (e.g. 'GLU') to abnormal probability (0.0 - 1.0).
final Map<String, double> knnProbabilities = {
  'GLU': {glu:.6f},
  'LEU': {leu:.6f},
  'PRO': {pro:.6f},
  'NIT': {nit:.6f},
};
"""


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--input', '-i', type=Path, default=Path('pipeline/dataset/latest_knn_probs.json'))
    p.add_argument('--output', '-o', type=Path, default=Path('uritect_app/lib/models/knn_probabilities.dart'))
    args = p.parse_args()

    if not args.input.exists():
        print(f'Input file not found: {args.input}')
        raise SystemExit(2)

    data = json.loads(args.input.read_text())

    def get_val(k):
        v = data.get(k)
        try:
            return float(v) if v is not None else 0.0
        except Exception:
            return 0.0

    out_text = TEMPLATE.format(
        glu=get_val('GLU'),
        leu=get_val('LEU'),
        pro=get_val('PRO'),
        nit=get_val('NIT'),
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(out_text, encoding='utf8')
    print(f'Wrote Dart KNN probabilities to: {args.output}')


if __name__ == '__main__':
    main()
